### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by yojeep** [lucidrains/gradnorm-pytorch#4]
import torch

from gradnorm_pytorch import (
    GradNormLossWeighter,
    MockNetworkWithMultipleLosses
)

# a mock network with multiple discriminator losses

network = MockNetworkWithMultipleLosses(
    dim = 512,
    num_losses = 4
)

# backbone shared parameter

backbone_parameter = network.backbone[-1].weight

# grad norm based loss weighter

loss_weighter = GradNormLossWeighter(
    num_losses = 4,
    learning_rate = 1e-4,
    restoring_force_alpha = 0.,                  # 0. is perfectly balanced losses, while anything greater than 1 would account for the relative training rates of each loss. in the paper, they go as high as 3.
    grad_norm_parameters = backbone_parameter
)

# mock input

mock_input = torch.randn(2, 512)
losses, backbone_output_activations = network(mock_input)

# backwards with the loss weights
# will update on each backward based on gradnorm algorithm

loss_weighter.backward(losses, retain_graph = True)

# if you would like to update the loss weights wrt activations just do the following instead

loss_weighter.backward(losses, backbone_output_activations)
![image](https://github.com/lucidrains/gradnorm-pytorch/assets/115990065/b609fd35-8582-471b-a2eb-8c507a75b3cd)

**Comment by Yangyx891121** [comment]
Same here.

**Comment by lucidrains** [comment]
@yojeep @Yangyx891121 oops, my bad

try 0.0.23?

**Comment by yojeep** [comment]
> @yojeep @Yangyx891121 oops, my bad
> 
> try 0.0.23?

It works, thanks a lot!

**Comment by Yangyx891121** [comment]
@lucidrains Thanks for the prompt update. I am still encountering a follow-up error though the example given in the readme runs successfully. The error is:

  File "/home/tiger/.local/lib/python3.9/site-packages/gradnorm_pytorch/gradnorm_pytorch.py", line 132, in backward
    return self.forward(*args, **kwargs)
  File "<@beartype(gradnorm_pytorch.gradnorm_pytorch.GradNormLossWeighter.forward) at 0x7fadab5b1280>", line 78, in forward
  File "/home/tiger/.local/lib/python3.9/site-packages/gradnorm_pytorch/gradnorm_pyt
orch.py", line 208, in forward
    initial_losses = maybe_distributed_mean(losses)
  File "/home/tiger/.local/lib/python3.9/site-packages/gradnorm_pytorch/gradnorm_pytorch.py", line 41, in maybe_distributed_mean
    return dist.all_reduce(t, dist.ReduceOp.MEAN)
AttributeError: type object 'torch._C._distributed_c10d.ReduceOp' has no attribute 'MEAN'

**Comment by lucidrains** [comment]
@Yangyx891121 ah yes, you are right

can you try 0.0.25?
